# Create a program that will play the “cows and bulls” game with the user. The game works like this:
#
# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number(Digits should not be repeated). For every digit that the user guessed correctly in the correct place, they have a “cow”. For every digit the user guessed correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have. Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.
#
# Say the number generated by the computer is 1038. An example interaction could look like this:
#
#   Welcome to the Cows and Bulls Game!
#   Enter a number:
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1250
#   1 cow, 1 bull
#   ...
# Until the user guesses the number.


import random
four_digit = str(random.randint(1000,9999))
digit_list = []
cow = 0
for i in four_digit:
    digit_list.append(i)
count=0
while cow < 4 and exit !="x":
    guess = str(input("Choose a 4 digit number, x to exit: "))
    guess_list = []
    count +=1
    cow = 0
    bull = 0
    if guess!= "x":
        for i in guess:
            guess_list.append(i)
        for i in digit_list:
            if i in guess_list and digit_list.index(i) == guess_list.index(i):
                cow +=1
            if i in guess_list and digit_list.index(i) != guess_list.index(i):
                bull +=1
        print(cow, "cow(s)", bull, "bull(s)")
    else:
        exit = "x"
print("Total number of attempts",count)
print(digit_list, guess_list)
